In [1]:
import pandas as pd

In [2]:
pd.read_csv('./data/GANData.csv')

,ASSETTYPE,ASSETSUBTYPE,ASSETNAME,ISHEDGED,INDEXPROXYNAME,VALUEDATE,PRICE
0,Alternative,Property,Global Property USD Unhedged,False,FTSE Russell FTSE EPRA Nareit Developed Index ...,36219,889.640000
1,Alternative,Property,Global Property USD Unhedged,False,FTSE Russell FTSE EPRA Nareit Developed Index ...,36250,916.070000
2,Alternative,Property,Global Property USD Unhedged,False,FTSE Russell FTSE EPRA Nareit Developed Index ...,36280,1006.430000
3,Alternative,Property,Global Property USD Unhedged,False,FTSE Russell FTSE EPRA Nareit Developed Index ...,36311,983.720000
4,Alternative,Property,Global Property USD Unhedged,False,FTSE Russell FTSE EPRA Nareit Developed Index ...,36341,1005.670000
...,...,...,...,...,...,...,...
36535,Risky FI,Corporate Bonds IG,USD Corporate Bond - USD Unhedged,False,Bloomberg U.S. Corporate Investment Grade Tota...,45155,2994.063762
36536,Risky FI,Corporate Bonds IG,USD Corporate Bond - USD Unhedged,False,Bloomberg U.S. Corporate Investment Grade Tota...,45156,3000.753902
36537,Risky FI,Corporate Bonds IG,USD Corporate Bond - USD Unhedged,False,Bloomberg U.S. Corporate Investment Grade Tota...,45159,2986.420876
36538,Risky FI,Corporate Bonds IG,USD Corporate Bond - USD Unhedged,False,Bloomberg U.S. Corporate Investment Grade Tota...,45160,2992.667990
36539,Risky FI,Corporate Bonds IG,USD Corporate Bond - USD Unhedged,False,Bloomberg U.S. Corporate Investment Grade Tota...,45161,3025.278091